version: "3.8"

services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: july-postgres
    environment:
      POSTGRES_DB: july_finance
      POSTGRES_USER: july_user
      POSTGRES_PASSWORD: july_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - july-network

  # Backend da aplicação
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: july-backend
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: july_finance
      DB_USER: july_user
      DB_PASSWORD: july_password
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRES_IN: 7d
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - july-network
    restart: unless-stopped

  # Nginx para servir o frontend e fazer proxy
  nginx:
    image: nginx:alpine
    container_name: july-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
    networks:
      - july-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  july-network:
    driver: bridge
